# Generated by Django 3.0.5 on 2022-05-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='fdate',
        ),
    ]
