# Generated by Django 3.0.5 on 2022-05-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasty', '0002_auto_20220520_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='D',
            field=models.DateField(auto_now=True),
        ),
    ]
