# Generated by Django 3.0.5 on 2022-05-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasty', '0004_auto_20220520_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='fdate',
            new_name='date',
        ),
    ]
